name: Atlas CI/CD
on:
  push:
    branches:
      - main # Use your main branch here.
  pull_request:

    paths:
      - 'migrations_destructive/*' # Use the path to your migration directory here.
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  atlas:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
      - uses: ariga/atlas-action/migrate/lint@v1
        with:
            dir: file://migrations_destructive
            dev-url: sqlite://file.db?mode=memory
            dir-name: test-dir-sqlite